import { Language } from './types';

export const TRANSLATIONS = {
  en: {
    appName: 'MedFinder',
    tagline: 'Addis Ababa Real-time Medicine & Pharmacy Search',
    searchPlaceholder: 'Search scarce medicines (e.g., Insulin, Ventolin, Clexane)...',
    subCityFilter: 'All Sub-Cities',
    currentLocation: 'Use My GPS Location',
    locationDetected: 'GPS Located',
    searching: 'Searching matching pharmacies...',
    noResults: 'No pharmacies currently report stock for this medicine in this area.',
    uploadPrescription: 'Upload Prescription',
    uploadSubtitle: 'Attach a photo of your prescription to find matching stock',
    inStock: 'In Stock',
    lowStock: 'Low Stock',
    outOfStock: 'Out of Stock',
    verified: 'Verified Pharmacy',
    open24Hours: 'Open 24 Hours',
    distanceAway: 'away',
    estimatedDrive: 'min drive',
    lastVerified: 'Stock checked',
    unlockToView: 'Unlock Contact & Hold',
    unlockDescription: 'Pay 20 ETB via Telebirr or Chapa to view direct phone number and reserve for 2 hours.',
    payWithTelebirr: 'Pay with Telebirr',
    payWithChapa: 'Pay with Chapa',
    reserveTitle: 'Hold Medicine (2-Hour Guarantee)',
    patientPhone: 'Your Phone Number (e.g., 0911...)',
    confirmReservation: 'Confirm & Reserve',
    reservationSuccess: 'Success! Medicine reserved for 2 hours.',
    pharmacyContact: 'Direct Pharmacy Phone:',
    pharmacyAddress: 'Exact Location:',
    callPharmacy: 'Call Pharmacy Now',
    scarceBadge: 'Scarce Medicine',
    quickFilters: 'Common In-Demand Medicines:',
    resultsFound: 'pharmacies found near',
    rxRequired: 'Rx Required',
    close: 'Close',
  },
  am: {
    appName: 'ሜድፋይንደር',
    tagline: 'በአዲስ አበባ ፈጣን የመድኃኒት እና የፋርማሲ ፈላጊ',
    searchPlaceholder: 'ብርቅዬ መድኃኒቶችን ይፈልጉ (ለምሳሌ ኢንሱሊን፣ ቬንቶሊን፣ ክሌክሴን)...',
    subCityFilter: 'ሁሉም ክፍለ ከተሞች',
    currentLocation: 'የአሁኑን መገኛዬን ተጠቀም',
    locationDetected: 'መገኛ ተገኝቷል',
    searching: 'ፋርማሲዎችን በመፈለግ ላይ...',
    noResults: 'በዚህ አካባቢ ይህን መድኃኒት የያዘ ፋርማሲ እስካሁን አልተገኘም።',
    uploadPrescription: 'የሐኪም ማዘዣ ጫን',
    uploadSubtitle: 'የሐኪም ማዘዣ ፎቶ በማያያዝ መድኃኒቱን ያሉበትን ፋርማሲዎች ያግኙ',
    inStock: 'በመጋዘን አለ',
    lowStock: 'አነስተኛ ክምችት',
    outOfStock: 'አልቋል',
    verified: 'የተረጋገጠ ፋርማሲ',
    open24Hours: '24 ሰዓት ክፍት',
    distanceAway: 'ርቀት',
    estimatedDrive: 'ደቂቃ በመኪና',
    lastVerified: 'ክምችት የተረጋገጠው',
    unlockToView: 'አድራሻ ክፈት እና ያዝ',
    unlockDescription: 'ቀጥታ የፋርማሲውን ስልክ ቁጥር ለማየትና መድኃኒቱን ለ2 ሰዓት ለማስያዝ 20 ብር በቴሌብር ወይም በቻፓ ይክፈሉ።',
    payWithTelebirr: 'በቴሌብር ክፈል',
    payWithChapa: 'በቻፓ ክፈል',
    reserveTitle: 'መድኃኒቱን ለ2 ሰዓት ያስቀምጡ',
    patientPhone: 'ስልክ ቁጥርዎ (ለምሳሌ 0911...)',
    confirmReservation: 'አረጋግጥ እና ያዝ',
    reservationSuccess: 'ተሳክቷል! መድኃኒቱ ለ2 ሰዓታት ተይዞሎታል።',
    pharmacyContact: 'የፋርማሲው ስልክ:',
    pharmacyAddress: 'ትክክለኛ አድራሻ:',
    callPharmacy: 'አሁን ወደ ፋርማሲው ደውል',
    scarceBadge: 'ብርቅዬ መድኃኒት',
    quickFilters: 'በብዛት የሚፈለጉ መድኃኒቶች:',
    resultsFound: 'ፋርማሲዎች ተገኝተዋል በአካባቢዎ',
    rxRequired: 'የሐኪም ማዘዣ ያስፈልጋል',
    close: 'ዝጋ',
  },
};

export function getTranslation(lang: Language) {
  return TRANSLATIONS[lang] || TRANSLATIONS.en;
}
